language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;'
  - mysql -e 'CREATE USER "nodeUser"@"localhost" IDENTIFIED BY "";'
  - mysql -e 'GRANT ALL ON *.* to "nodeUser"@"localhost" WHITH GRANT OPTION;'
env:
  global:
    - describe
# test:
#   adapter: mysql2
#   database: testdb
#   username: nodeUser
#   encoding: utf8